# Checkov configuration for security scanning
# Skips are justified with comments explaining why each check is not applicable

skip-check:
  # CloudFront Checks
  - CKV_AWS_310  # Origin failover requires multiple origins - not needed for single instance
  - CKV_AWS_68   # WAF is optional and adds cost - can be enabled via waf_web_acl_id variable
  - CKV2_AWS_47  # WAF Log4j rules require WAF to be enabled first
  - CKV2_AWS_42  # Custom SSL requires domain ownership - using CloudFront default
  
  # Secrets Manager Checks
  - CKV2_AWS_57  # Automatic rotation not needed - secret is randomly generated and internal
  
  # Security Group Checks  
  - CKV_AWS_382  # Egress 0.0.0.0/0 required for OS updates via NAT - instance has no public IP
